name: GroupPVP
version: 0.1
author: rfsantos1996
main: com.jabyftw.gpvp.GroupPVP
description: PVP Groups on MySQL
commands:
   gpvp:
     description: Main command
     usage: Use /gpvp (create/invite/kick) (name)
permissions:
   dotamine.play:
     description: Gives access to the main command
     default: true