name: GroupPVP
version: 0.2.3
author: rfsantos1996
main: com.jabyftw.gpvp.GroupPVP
description: PVP Groups on MySQL
commands:
   gpvp:
     description: Main command
     usage: Use /gpvp (create/invite/kick/setbase/delete) (name)
permissions:
   gpvp.use:
     description: Gives access to use the plugin
     default: true